library(stringr)
library(soiltexture)
library(assertthat)


.generatePEDON <- function(PEDON = "", .institute = "MZ", .site = "CO", .year = NA_real_, .id) {
  if (PEDON == "") {
    .institute <- str_to_upper(substr(.institute, 1, 2))
    .site <- str_to_upper(substr(.site, 1, 2))
    .site <- ifelse(.site == "" | nchar(.site) < 2 | is.na(.site) | !grepl("^[a-zA-Z]+$", .site), "ZZ", .site)
    .year <- ifelse(is.na(.year), as.integer(format(Sys.Date(), "%Y")), .year)
    .year <- substr(as.character(.year), 3, 4)
    .id <- sprintf("%04d", .id)
    PEDON <- paste0(.institute, .site, .year, .id)
  }
  return(PEDON)
}

.adjustPercentages <- function(clay, silt, sand) {
  clay <- as.numeric(clay)
  silt <- as.numeric(silt)
  sand <- as.numeric(sand)
  total <- clay + silt + sand

  if (any(is.na(total))) {
    return(cbind(CLAY = NA, SILT = NA, SAND = NA))
  }
  if (any(total != 100)) {
    clay <- clay / total * 100
    silt <- silt / total * 100
    sand <- sand / total * 100
  }
  return(cbind(CLAY = clay, SILT = silt, SAND = sand))
}

.getSoilTexture <- function(clay, silt, sand) {
  .tri.data <- .adjustPercentages(clay, silt, sand)
  .tri.data <- as.data.frame(.tri.data)
  
  # texture_matrix <- soiltexture::TT.points.in.classes(tri.data = .tri.data,
  #                                                     text.sum = .tri.data[["total"]],
  #                                                     class.sys = "USDA.TT")
  
  texture_matrix <- tryCatch({
    soiltexture::TT.points.in.classes(tri.data = .tri.data,
                                      text.sum = .tri.data[["total"]],
                                      class.sys = "USDA.TT")
  }, error = function(e) {
    return(NA_character_)
  })
  
  if (is.character(texture_matrix) && is.na(texture_matrix)) {
    return(NA_character_)
  }
  
  stopifnot("Autogenerated soil texture is not classifying the same number of samples as the soil input data.
              Each soil input row must have a corresponding soil texture classification." = assertthat::assert_that(dim(.tri.data)[1] == dim(texture_matrix)[1]))
  columns <- which(texture_matrix == 1, arr.ind = TRUE)[, 2]
  texture <- colnames(texture_matrix)[columns]
  
  textures_names <- list(Sa = "sand",
                         LoSa = "loamy sand",
                         SaLo = "sandy loam",
                         Lo = "loam",
                         SiLo = "silt loam",
                         Si = "silt",
                         SaClLo = "sandy clay loam",
                         ClLo = "clay loam",
                         SiClLo = "silty clay loam",
                         SaCl = "sandy clay",
                         SiCl = "silty clay",
                         Cl = "clay")
  return(as.character(textures_names[texture]))
}